name: Build and Run Workflow

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0' # Update to the desired .NET version

      - name: Build and Publish
        run: |
          cd lesson1
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish

      - name: Run the executable
        run: |
          cd lesson1/publish
          dotnet ./lesson1.dll
